apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kbnv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kbnv
    app.kubernetes.io/part-of: integ-app-wohn
  name: hacbs-test-project-kbnv
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kbnv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kbnv
    spec:
      containers:
      - image: quay.io/bootstrap/integration2-wqud-tenant/integ-app-wohn/hacbs-test-project-kbnv@sha256:53a49ae60e0cbaab4e4e72bdbe4c715f69abc0bb20a16c2a5e2fc2980b93b413
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
